<a href="https://colab.research.google.com/github/hyui02/ESAA_assignment/blob/main/ESAA_YB_WEEK1_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.3 넘파이(Numpy)
  - 선형대수 기반의 프로그래밍을 쉽게 만드는 패키지
    * 특징
      - 배열 기반의 연산 및 데이터 핸들링 기능 제공
      - 빠른 배열 속도
      - 편의성과 다양한 API 지원 측면의 아쉬움 -> 가공과 변환, 여러 가지 통계용 함수 적용 등 요구

### 1.3.1 ndarray
  - 다차원 배열 생성 및 다양한 연산 수행
  - shape 변수: ndarray 크기(m*n)를 튜플 형태로 갖고 있음 -> 차원 확인 가능
  - []의 개수에 따라 동일한 데이터 건수도 차원을 달리할 수 있다.

In [1]:
import numpy as np

array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:',array1.shape) #차원과 크기를 튜플 형태로

array2=np.array([[1,2,3],[2,3,4]]) # 수정된 부분: 두 리스트를 하나의 리스트로 감쌈
print('array2 type:', type(array2))
print('array2 array 형태:',array2.shape) #차원과 크기를 튜플 형태로

array3=np.array([[1,2,3]])
print('array2 type:', type(array3))
print('array2 array 형태:',array3.shape) #차원과 크기를 튜플 형태로

print('array1：{0}차원, array2： {1}차원, array3： {2}차원'.format(array1 .ndim, array2.ndim, array3.ndim))


array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (1, 3)
array1：1차원, array2： 2차원, array3： 2차원


## 1.3.2 ndarray의 데이터 타입

- 숫자 값(int/float/complex), 문자열 값, 불 값 등 가능
-  연산의 특성상 같은 데이터 타입만 가능

  1. 다른 유형 혼합 리스트-> ndarray: 더 큰 데이터 타입으로 변경
  2. ndarray 내 변경: astype()





In [2]:

list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

list2= [1,2,'test'] #int+str
array2=np.array(list2)
print(array2, array2.dtype) #결과값=> int< str

list3=[1,2,3.0] #int+float
array3=np.array(list3)
print(array3, array3.dtype) #결과값=> int<float

array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64
[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


###1.3.3 arange, zeros, ones
-  테스트용 데이터 생성 및 데이터 일괄 초기화 시 주로 사용됨

1.   arange 함수
  -  array를 range로 표현
  - range(n): 0~n-1 나열
  - range(n,m): n~m-1 나열
2.   zeros 함수
  - 모든 값을 0으로 채운 ndarray를 반환
3. ones 함수
- 모든 값을 1로 채운 ndarray를 반환

In [3]:

# 1. arange 함수
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

# 2. zeros 함수
zero_array=np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape) # .shape=> 배열의 모양을 튜플로 알려줌

# 3. ones 함수
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


###1.3.4 ndarray의 차원과 크기를 변경하는 reshape()
- ndarray를 특정 차원 및 크기로 변환
- -1 인자 사용 多: 한쪽(-1 x) 축을 고정하고, 나머지(-1) 축을 차원 크기를 원본과 호환되게 자동 계산

- tolist(): ndarray -> 리스트

In [4]:
array1=np.arange(10)
print('array1:\n', array1)

array2=array1.reshape(2,5)
print('array2:\n', array2)

array3=array1.reshape(5,2)
print('array3:\n', array3)


array1=np.arange(8)
array3d= array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


###1.3.5 넘파이의 ndarray의 데이터 세트 선택하기- 인덱싱

1.  특정 값 추출: [] 안에 인덱스를 넣어 원하는 위치의 값을 1개 꺼내는 방법

2. 슬라이싱: ':'를 이용해 연속된 데이터 추출 => 'a:b', 인덱스 a부터 b-1까지 추출

3. 팬시 인덱싱: 인덱스 리스트/ndarray -> 해당 위치 값 반환

4. 불린 인덱싱: 조건 필터링과 검색이 동시에 가능한 인덱싱



In [5]:
#1. 특정 값 추출
# 1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1,stop=10)
print(' array1:', array1)

#index는 0부터 시작하므로 arrayl[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:', value)
print(type(value))

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

array1[0]=9
array1[8]=0
print('array1:', array1)



array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)
print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1 ])
print('(row=1, col=O) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])


#2. 슬라이싱
# 1차원
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

array1 = np.arange(start=1, stop=10)
array4 = array1[:3] #처음 인덱스가 0으로 간주
print(array4)

array5 = array1[3:] #종료 인덱스가 맨 마지막 인덱스로 간주
print(array5)

array6 = array1[:] #시작/종료 인덱스를 맨 처음/마지막 인덱스로 간주
print(array6)

#2차원
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, array2d[0:2,0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3,0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3,:]\n', array2d[1:3, :])
print('array2d[:,:]\n', array2d[:, :])
print('array2d[:2,1:]\n', array2d[:2, 1:])
print('array2d[:2,0]\n', array2d[:2, 0])

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

# 3. 팬시인덱싱

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2] # 행 인덱스 리스트, 열 인덱스
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] => ', array4.tolist())

array5= array2d[[0, 1]]
print('array2d[[0, 1]] => ', array5.tolist())



# 4. 불린인덱싱

array1d=np.arange(start=1,stop=10)
#[] 안에 array1d> 5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',array3)

array1d>5 #True,False로 출력

boolean_indexes =np.array([False,False,False,False,False,True,True,True,True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)




 array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=O) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9
[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)
array2d[[0, 1], 2] =>  [3, 6]
array2d[[0, 1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0, 1]] =>  [[1, 2, 3], [4, 5, 6]]
array1d>5 불린 인덱싱 결과 값: [6 7 8 9]
불린 인덱스로 필터링 결과: [6 7 8 9]
일반 인덱스로 필터링 결과: [6 7 8 9]


## 1.3.6 행렬의 정렬- sort()와 argsort()
1. 행렬 정렬
  - np.sort(): 원본 행렬 유지, 정렬 행렬 반환
  - ndarray.sort(): 원본 행렬-> 정렬 행렬, 반환 값: none
  
  + [::-1]=> 내림차순 정렬

2. 정렬된 행렬의 인덱스를 반환하기
- np.argsort(): 정렬 행렬-> 원본 행렬

In [6]:
#1. 행렬 정렬
org_array=np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

#ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)
sort_array1_desc= np.sort(org_array)[::-1] #[::-1]은 내림차순 정렬
print('내림차순으로 정렬:',sort_array1_desc)
array2d=np.array([[8,12],[7,1]])

sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

# 2. 정렬된 행렬의 인덱스를 반환하기

org_array=np.array([3,1,9,5])
sort_indices= np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)
org_array=np.array([3,1,9,5])
sort_indices_desc= np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

import numpy as np

name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:',name_array[sort_indices_asc])




원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]
성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 1.3.7 선형대수 연산- 행렬 내적과 전치 행렬 구하기
1. 행렬 내적(행렬곱)
  - np.dot()

2. 전치 행렬
  - transpose()

In [7]:
#1. 행렬 내적
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

#2. 전치행렬
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]
A의 전치 행렬:
 [[1 3]
 [2 4]]


##