<a href="https://colab.research.google.com/github/hyui02/ESAA_assignment/blob/main/YB_0904_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [9]:
matrix_one=np.dot(np.ones((5,3)),np.ones((3,2)))
print(matrix_one)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [10]:
m_1=np.random.random((5,3))
m_2=np.random.random((3,2))
print(np.dot(m_1,m_2))

[[1.19037636 0.80284295]
 [0.61121474 0.56554489]
 [0.66239386 0.54475272]
 [1.3980297  1.17014462]
 [1.14635798 0.80330609]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [11]:
array_1d=np.arange(10)
array_1d[(array_1d>3)&(array_1d<8)]*=-1
print(array_1d)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [13]:
print(sum(range(5),-1)) #여기서 -1은 덧셈의 연장선으로 인식
from numpy import *
print(sum(range(5),-1)) #여기서 -1은 축으로 인식 => 원인: from numpy import

10
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

마지막 줄을 제외한 나머지 다 ok
Z<Z>Z -> 연쇄비교를 할 경우, and 연사자를 사용한다. numpy 배열은 원소가 여러 개면 참/ 거짓을 하나로 판단 불가하므로 에러 발생


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [2]:
import numpy as np
np.array(0)

array(0)

In [12]:
np.array(0) / np.array(0) #0에서 0을 나누는 건 수학적 정의에 어긋나기 때문에
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [21]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[5 7 8 9]


##조원 스터디 파트 27-32

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [3]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_2799/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [5]:
z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [9]:
A=np.random.random((4,4))
B=np.random.random((4,4))
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([[-0.12853261, -0.00492869, -0.05381411, -0.70767162],
       [-0.02350201, -0.30219136, -0.00536192, -0.05942964],
       [-0.15052313, -0.06762156, -0.80000378, -0.34676525],
       [-0.06952055, -0.45092194, -0.48912702, -0.00563434]])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [10]:
z = np.random.uniform(0, 10, 10)
print(z)
print(z - z % 1)
print(z // 1)

[0.43183016 6.71520998 2.1222324  6.25562926 4.37803642 1.54206802
 8.69028116 0.46578046 6.71000659 6.49104287]
[0. 6. 2. 6. 4. 1. 8. 0. 6. 6.]
[0. 6. 2. 6. 4. 1. 8. 0. 6. 6.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [11]:
z = np.zeros((5,5)) + np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [6]:
z = np.random.random(10)
z.sort()
print(z)

[0.04583996 0.08158974 0.08325291 0.2078425  0.26598983 0.30740234
 0.31522913 0.48659207 0.64503533 0.81206759]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [15]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(np.array_equal(A,B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [22]:
z=np.random.random((10,2))
x,y=z[:,0],z[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[0.79862913 0.8447393  0.50872749 0.27803087 0.41319484 0.96201416
 0.62431326 0.5906045  0.72872911 0.2964483 ]
[1.25282954 1.14458882 0.25677661 1.38071361 0.74235184 0.18320681
 1.02521285 0.2589903  1.2455525  0.19439581]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [16]:
z=np.random.random(10)
z[z.argmax()]=0
print(z)


[0.57711322 0.46411807 0.         0.51382286 0.83400863 0.12686188
 0.62045163 0.82228993 0.57147987 0.03718499]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [17]:
Z = np.arange(100)
v = np.random.uniform(0,100)

index=(np.abs(Z-v)).argmin()
print(Z[index])

71


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [20]:
z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [12]:
n=5
p=3

Z=np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),1)
print(Z)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [19]:
z=np.random.randint(0,10,(3,3))
print(z[z[:,1].argsort()])

[[8 5 5]
 [2 6 5]
 [8 8 1]]
